spring:
  application:
    name: greeting-service

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

# Actuator config
management:
  # Actuator config to expose or exclude resources endpoints
  endpoints:
    web:
      exposure:
        include:
          - '*'
  # Actuator config to show all details from endpoint /health
  endpoint:
    health:
      show-details: ALWAYS

greeting-service:
  greeting: "Hola"
  defaultValue: "Mundo"